# Build stage
FROM maven:3.9.6-eclipse-temurin-21 AS builder
WORKDIR /app

# Dependencias primero para aprovechar cache
COPY pom.xml .
RUN mvn -B -DskipTests dependency:go-offline

# Código fuente
COPY src ./src

# Empaquetar (sin tests para acelerar la imagen)
RUN mvn -B -DskipTests clean package

# Runtime stage
FROM eclipse-temurin:21-jre
WORKDIR /app

# Copiamos el jar construido
COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java","-jar","/app/app.jar"]
